name       : python-funcsigs
version    : 1.0.2
release    : 1
source     :
    - https://pypi.python.org/packages/94/4a/db842e7a0545de1cdb0439bb80e6e42dfe82aaeaadd4072f2263a4fbed23/funcsigs-1.0.2.tar.gz : a7bb0f2cf3a3fd1ab2732cb49eba4252c2af4240442415b4abce3b87022a8f50
license    : Apache-2.0
component  : programming.python
summary    : Python function signatures from PEP362
description: |
    Python function signatures from PEP362
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install